theme: jekyll-theme-slate
title: Roheet N Rajendran
github:
  repository_url: https://github.com/roheetnarayanan
  
layout: page
title: "Certifications"
permalink: https://roheetnarayanan.github.io/Certifications/
