theme: jekyll-theme-slate
title: Roheet Narayanan Rajendran
baseurl: /
github:
  repository_url: https://github.com/roheetnarayanan
  
layout: page
permalink: https://roheetnarayanan.github.io/Certifications/
