theme: jekyll-theme-slate
name: Roheet Narayanan Rajendran
title: null
github:
  repository_url: https://github.com/roheetnarayanan
  
layout: page
permalink: https://roheetnarayanan.github.io/Certifications/
